name: Deploy to Server


on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get install sshpass -y

      - name: Deploy to Server
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /opt/emc-event-backend
          git pull origin main
          sudo systemctl stop dev
          sudo systemctl restart prod
          EOF
